name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build

      - name: Lint Code with flake8
        run: flake8 mypackage/

      - name: Check Formatting with black
        run: black --check mypackage/

      - name: Run Tests
        run: pytest mypackage/

      - name: Build Package
        run: python -m build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-build
          path: dist/
